<style type="text/css">
html, body {
	background-color: #fff;
	color: #000;
}
.divDebug table, td {
	border-collapse: collapse;
}
.divDebug {
	border: 1px #111 outset;
	background-color:#88c0b8;
	padding:5px;
}
.divTitle {
	font-size:2em;
	font-weight:bold;
	padding:5px;
}
.tblDebug, .tblDebug td {
	border:1px #111 outset;
	font-size:12px;
}
.tblDebug td {
	padding:5px;
}
.tblDebug .tdDate {
	width:150px;
}
.tblDebug .tdTime {
	text-align:center;
}
.tblDebug .tdMemory {
	text-align:right;
}
</style>
<div class="divDebug">
  <div class="divTitle">系统开销</div>
  <table class="tblDebug">
    <tr>
      <td>模块</td>
      <td class="tdTime">耗时</td>
      <td class="tdMemory">内存开销(byte)</td>
    </tr>
    <?php foreach($aHtml['aDebugInfo'] as $sDebugType =>$aDebugInfo){ ?>
    <tr>
      <td><?php echo $sDebugType; ?></td>
      <td class="tdTime"><?php echo number_format($aDebugInfo['fTimeCost'],8); ?></td>
      <td class="tdMemory"><?php echo number_format($aDebugInfo['iMemoryCost']); ?></td>
    </tr>
    <?php } ?>
  </table>
  <div class="divTitle">系统信息</div>
  <table class="tblDebug">
    <tr>
      <td class="tdTime tdDate">发送时间</td>
      <td class="tdTime">相对时间</td>
      <td>内容</td>
    </tr>
    <?php foreach($aData['aDebugMsg'] as $aDebugMsg){ ?>
    <tr>
      <td class="tdTime"><?php echo date('Y-m-d H:i:s',$aDebugMsg['fTime']); ?></td>
      <td class="tdTime"><?php echo number_format($aDebugMsg['fTimeCost'],8); ?></td>
      <td><?php echo $aDebugMsg['sMsg']; ?></td>
    </tr>
    <?php } ?>
  </table>
  <div class="divTitle">系统参数</div>
  <table class="tblDebug">
    <tr>
      <td>POST</td>
      <td><table>
          <?php foreach($aHtml['aDebugParam']['aPost'] as $sKey => $mValue ){ ?>
          <tr>
            <td><?php echo $sKey; ?></td>
            <td><?php echo $mValue; ?></td>
          </tr>
          <?php } ?>
        </table></td>
    </tr>
    <tr>
      <td>GET</td>
      <td><table>
          <?php foreach($aHtml['aDebugParam']['aGet'] as $sKey => $mValue ){ ?>
          <tr>
            <td><?php echo $sKey; ?></td>
            <td><?php echo $mValue; ?></td>
          </tr>
          <?php } ?>
        </table></td>
    </tr>
    <tr>
      <td>URL</td>
      <td><table>
          <?php foreach($aHtml['aDebugParam']['aURL'] as $sKey => $mValue ){ ?>
          <tr>
            <td><?php echo $sKey; ?></td>
            <td><?php echo $mValue; ?></td>
          </tr>
          <?php } ?>
        </table></td>
    </tr>
    <tr>
      <td>COOKIE</td>
      <td><table>
          <?php foreach($aHtml['aDebugParam']['aCookie'] as $sKey => $mValue ){ ?>
          <tr>
            <td><?php echo $sKey; ?></td>
            <td><?php echo $mValue; ?></td>
          </tr>
          <?php } ?>
        </table></td>
    </tr>
    <tr>
      <td>SERVER</td>
      <td><table>
          <?php foreach($aHtml['aDebugParam']['aServer'] as $sKey => $mValue ){ ?>
          <tr>
            <td><?php echo $sKey; ?></td>
            <td><?php echo $mValue; ?></td>
          </tr>
          <?php } ?>
        </table></td>
    </tr>
    <tr>
      <td>CONFIG</td>
      <td><table>
          <?php foreach($aHtml['aDebugParam']['aConfig'] as $sKey => $mValue ){ ?>
          <tr>
            <td><?php echo $sKey; ?></td>
            <td><table>
                <?php foreach($mValue as $sSubKey => $mSubValue){ ?>
                <tr>
                  <td><?php echo $sSubKey; ?></td>
                  <td><?php
                            if(is_bool($mSubValue)){
                                echo $mSubValue?'true':'false';
                            }else{
                                print_r($mSubValue);
                            }
                        ?>
                  </td>
                </tr>
                <?php } ?>
              </table></td>
          </tr>
          <?php } ?>
        </table></td>
    </tr>
  </table>
</div>
